### ISSUE TITLE
FlxBackdrop doesn't support custom alpha

### ISSUE THREAD

**Issue by ivodopiviz** [HaxeFlixel/flixel-addons#241]
As the title says, even though you can set the alpha because it inherits from FlxSprite, it doesn't have any effect.

I already have code for both renderBlit and quadBatch render paths that I'm going to clean up. I'll submit a PR later.

**Comment by diegosolo** [comment]
Hi! There seems to be a problem with this implementation in Flash targets. the problem is that your line...

camera.copyPixels(frame, framePixels, _flashRect2, _ppoint, _colorTransform);

...goes to the FlxCamera function copyPixels that only considers the transform parameter if the render mode isn't FlxG.renderBlit. I don't know how to go further from that as, if you continue digging, you end up in OpenFL source files. Do you think this can be solved?

**Comment by diegosolo** [comment]
Hi! I managed to fix it by replacing this...

	_flashRect2.setTo(0, 0, graphic.width, graphic.height);
	camera.copyPixels(frame, famePixels, _flashRect2, _ppoint);

... by this...

	_flashRect2.setTo(0, 0, graphic.width, graphic.height);
	var tempFramePixels: BitmapData = framePixels.clone();
	tempFramePixels.colorTransform(_flashRect2, _colorTransform);
	camera.copyPixels(frame, tempFramePixels, _flashRect2, _ppoint);

Certainly, making a clone in every draw isn't the best approach, but I failed trying to create and initialize the BitmapData in the beginning and then use copyPixels instead of clone. I think you have to adjust width and height every time regenGraphic is called... wait, I'll try more...

**Comment by diegosolo** [comment]
There I got it! Yet, I'd like others to review the code, I'm not sure about calling new in the regenGraphic function. I'll try to do a PR (never done that before)...

**Comment by ivodopiviz** [comment]
Please note that I never sent a pull request to that code because I think there's a cleaner solution. Unfortunately, I'm trying to finish a game and don't currently have the time to implement that fix.

**Comment by diegosolo** [comment]
Can I do it? (Sorry, I'm new)...

**Comment by ivodopiviz** [comment]
That's no my decision to make, but I certainly doubt the HaxeFlixel teams would mind getting a patch for this.

**Comment by diegosolo** [comment]
Ok, I'm not sure what I did, but I think I added the modifications to the dev branch. I guess they should review and (hopefully) aproove now. Hope didn't mess it up...
